### ISSUE TITLE
Stop lying on GitHub

### ISSUE THREAD

**Issue by cpiotr** [moncefmechri/SimpleCPU#1] opened 2017-03-22 23:57 UTC
The project name says `SimpleCPU`. It clearly is not simple.
Please, fix the name or simplify the project.

**Comment by moncefmechri** [comment] 2017-03-23 00:39
CAN'T REPRODUCE, WON'T FIX

**Closed as completed** 2017-03-23 00:39 UTC

**Comment by cpiotr** [comment] 2017-03-23 00:40
All caps, sophisticated. 
Thanks for your time, sir.

**Comment by mguby** [comment] 2017-03-23 00:43
🤔🤔🤔
